```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## May 31, 2019
by mas

```{r, echo=FALSE}
library(leaflet)

lat <- c(39.956302, 39.953970, 39.952831, 39.952490, 39.954640, 39.953595, 39.953077, 39.950906, 39.951087, 39.947747, 39.953538, 39.953210, 39.951193, 39.954829, 39.954841) 

lng <- c(-75.202234, -75.200343, -75.203063, -75.199370, -75.194883, -75.193177, -75.192233, -75.195022, -75.198225, -75.192560, -75.192545, -75.193193, -75.199008, -75.202301, -75.202298)

penn_coffee <- data.frame(lat, lng)

sites <- c(
        "<a href=https://www.yelp.com/biz/green-line-cafe-philadelphia-7>Green Line Cafe</a>", 
        "<a href=https://www.yelp.com/biz/starbucks-philadelphia-70>Starbucks</a>",
        "<a href=https://www.yelp.com/biz/saxbys-coffee-philadelphia-35>Saxby's</a>",
        "<a href=https://www.yelp.com/biz/starbucks-philadelphia-29>Starbucks</a>",
        "<a href=https://www.yelp.com/biz/wawa-philadelphia-28>Wawa</a>",
        "<a href=https://www.yelp.com/biz/federal-donuts-philadelphia-5>Federal Donuts</a>",
        "<a href=https://www.yelp.com/biz/starbucks-philadelphia-64>Starbucks</a>",
        "<a href=https://www.yelp.com/biz/williams-cafe-philadelphia-2>William's Cafe</a>",
        "<a href=https://www.yelp.com/biz/kitchen-gia-philadelphia>Kitchen Gia</a>",
        "<a href=https://www.yelp.com/biz/gia-pronto-philadelphia-5>Gia Pronto</a>",
        "<a href=https://www.yelp.com/biz/avril-50-philadelphia>Avril 50</a>",
        "<a href=https://www.yelp.com/biz/united-by-blue-philadelphia-3>United by Blue</a>",
        "<a href=https://www.yelp.com/biz/wawa-philadelphia-29>Wawa</a>",
        "<a href=https://www.yelp.com/biz/dunkin-donuts-philadelphia-153>Dunkin'</a>",
        "<a href=https://www.yelp.com/biz/dunkin-donuts-philadelphia-40>Dunkin'</a>")

penn_coffee %>% leaflet() %>% 
        addTiles() %>% 
        addMarkers(popup=sites)
```
